//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeliculasSW.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libro
    {
        public int IdLibro { get; set; }
        public string Titulo { get; set; }
        public string FechaLanzamiento { get; set; }
        public int Autor { get; set; }
        public int Categoria { get; set; }
        public int Editorial { get; set; }
        public string Idioma { get; set; }
        public string Descripcion { get; set; }
    }
}
